apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-28T06:15:38Z"
    name: default
    namespace: monitoring
    resourceVersion: "77345"
    uid: 9157edad-235d-417e-88dd-cf3efab02065
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-08-28T08:50:04Z"
    labels:
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 12.1.0
      helm.sh/chart: grafana-9.3.6
    name: kube-prometheus-grafana
    namespace: monitoring
    resourceVersion: "104179"
    uid: 5e6a22f8-b75e-4306-abb1-348d8387d4e6
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-08-28T08:50:04Z"
    labels:
      app: kube-prometheus-stack-alertmanager
      app.kubernetes.io/component: alertmanager
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-alertmanager
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 77.0.2
      chart: kube-prometheus-stack-77.0.2
      heritage: Helm
      release: kube-prometheus
    name: kube-prometheus-kube-prome-alertmanager
    namespace: monitoring
    resourceVersion: "104180"
    uid: 2f10596c-edc9-4296-81fd-e0bdf862b698
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-08-28T08:50:04Z"
    labels:
      app: kube-prometheus-stack-operator
      app.kubernetes.io/component: prometheus-operator
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 77.0.2
      chart: kube-prometheus-stack-77.0.2
      heritage: Helm
      release: kube-prometheus
    name: kube-prometheus-kube-prome-operator
    namespace: monitoring
    resourceVersion: "104178"
    uid: 3fb486d8-96b5-4ec7-9e47-27b67dfd47d5
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-08-28T08:50:04Z"
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-prometheus
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 77.0.2
      chart: kube-prometheus-stack-77.0.2
      heritage: Helm
      release: kube-prometheus
    name: kube-prometheus-kube-prome-prometheus
    namespace: monitoring
    resourceVersion: "104183"
    uid: 4d2ba778-97ba-4cf4-a524-5aef24143e2d
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-08-28T08:50:04Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-state-metrics
      app.kubernetes.io/version: 2.16.0
      helm.sh/chart: kube-state-metrics-6.1.5
      release: kube-prometheus
    name: kube-prometheus-kube-state-metrics
    namespace: monitoring
    resourceVersion: "104181"
    uid: 61d6fc8e-4a59-4cf2-bdb8-00f4d68090e8
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-08-28T08:50:04Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus-node-exporter
      app.kubernetes.io/part-of: prometheus-node-exporter
      app.kubernetes.io/version: 1.9.1
      helm.sh/chart: prometheus-node-exporter-4.47.3
      release: kube-prometheus
    name: kube-prometheus-prometheus-node-exporter
    namespace: monitoring
    resourceVersion: "104182"
    uid: 7cd5af01-fc4d-4a88-9c50-1177a1c2720f
kind: List
metadata:
  resourceVersion: ""
