apiVersion: v1
items:
- apiVersion: operator.tigera.io/v1
  kind: APIServer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.tigera.io/v1","kind":"APIServer","metadata":{"annotations":{},"name":"default"},"spec":{}}
    creationTimestamp: "2025-08-27T01:42:29Z"
    generation: 1
    name: default
    resourceVersion: "877180"
    uid: 790cb36e-1494-48d4-b189-1ddf9fa3d0be
  spec: {}
  status:
    conditions:
    - lastTransitionTime: "2025-09-01T09:57:28Z"
      message: Deployment "calico-apiserver/calico-apiserver" is not available (awaiting
        1 replicas)
      observedGeneration: 1
      reason: ResourceNotReady
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-09-01T09:57:28Z"
      message: ""
      observedGeneration: 1
      reason: Unknown
      status: "False"
      type: Degraded
    - lastTransitionTime: "2025-09-01T09:57:28Z"
      message: ""
      observedGeneration: 1
      reason: Unknown
      status: "False"
      type: Ready
    state: Ready
kind: List
metadata:
  resourceVersion: ""
