apiVersion: v1
items:
- apiVersion: projectcalico.org/v3
  kind: BlockAffinity
  metadata:
    creationTimestamp: "2025-08-27T02:01:11Z"
    name: k8s-backend-10-244-148-192-26
    resourceVersion: "3956"
    uid: a6d96c24-66c7-416f-8f37-ce73e99faebc
  spec:
    cidr: 10.244.148.192/26
    node: k8s-backend
    state: confirmed
- apiVersion: projectcalico.org/v3
  kind: BlockAffinity
  metadata:
    creationTimestamp: "2025-08-27T02:18:27Z"
    name: k8s-frontend-10-244-58-0-26
    resourceVersion: "6112"
    uid: 7d8d3bfe-16b5-410c-bd7c-961f10d25975
  spec:
    cidr: 10.244.58.0/26
    node: k8s-frontend
    state: confirmed
- apiVersion: projectcalico.org/v3
  kind: BlockAffinity
  metadata:
    creationTimestamp: "2025-08-27T01:43:44Z"
    name: k8s-master-cp-10-244-43-0-26
    resourceVersion: "1593"
    uid: 2e10994e-3132-43a5-8c5f-41e7c87b4c48
  spec:
    cidr: 10.244.43.0/26
    node: k8s-master-cp
    state: confirmed
- apiVersion: projectcalico.org/v3
  kind: BlockAffinity
  metadata:
    creationTimestamp: "2025-08-27T01:43:48Z"
    name: k8s-monitoring-10-244-134-192-26
    resourceVersion: "1658"
    uid: 08ee4d94-6894-4332-9fa4-a33892edefe6
  spec:
    cidr: 10.244.134.192/26
    node: k8s-monitoring
    state: confirmed
kind: List
metadata:
  resourceVersion: ""
