apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: BlockAffinity
  metadata:
    annotations:
      projectcalico.org/metadata: '{"creationTimestamp":null}'
    creationTimestamp: "2025-08-27T02:01:11Z"
    generation: 2
    name: k8s-backend-10-244-148-192-26
    resourceVersion: "3956"
    uid: 659b3624-66e3-41f6-8fec-73ce97f9753d
  spec:
    cidr: 10.244.148.192/26
    deleted: "false"
    node: k8s-backend
    state: confirmed
    type: host
- apiVersion: crd.projectcalico.org/v1
  kind: BlockAffinity
  metadata:
    annotations:
      projectcalico.org/metadata: '{"creationTimestamp":null}'
    creationTimestamp: "2025-08-27T02:18:27Z"
    generation: 2
    name: k8s-frontend-10-244-58-0-26
    resourceVersion: "6112"
    uid: beb1dc7f-68ad-4130-bd3e-69f8084b9aae
  spec:
    cidr: 10.244.58.0/26
    deleted: "false"
    node: k8s-frontend
    state: confirmed
    type: host
- apiVersion: crd.projectcalico.org/v1
  kind: BlockAffinity
  metadata:
    annotations:
      projectcalico.org/metadata: '{"creationTimestamp":null}'
    creationTimestamp: "2025-08-27T01:43:44Z"
    generation: 2
    name: k8s-master-cp-10-244-43-0-26
    resourceVersion: "1593"
    uid: 74089972-8c4c-43a5-8cfa-82e713de3212
  spec:
    cidr: 10.244.43.0/26
    deleted: "false"
    node: k8s-master-cp
    state: confirmed
    type: host
- apiVersion: crd.projectcalico.org/v1
  kind: BlockAffinity
  metadata:
    annotations:
      projectcalico.org/metadata: '{"creationTimestamp":null}'
    creationTimestamp: "2025-08-27T01:43:48Z"
    generation: 2
    name: k8s-monitoring-10-244-134-192-26
    resourceVersion: "1658"
    uid: 1077b229-1629-434c-9f25-c51c49b7f767
  spec:
    cidr: 10.244.134.192/26
    deleted: "false"
    node: k8s-monitoring
    state: confirmed
    type: host
kind: List
metadata:
  resourceVersion: ""
