apiVersion: v1
items:
- apiVersion: projectcalico.org/v3
  kind: FelixConfiguration
  metadata:
    creationTimestamp: "2025-08-27T01:42:38Z"
    generation: 1
    name: default
    resourceVersion: "177414"
    uid: 199c164d-17cd-4048-b62f-9ce0bbcfdf12
  spec:
    bpfConnectTimeLoadBalancing: TCP
    bpfHostNetworkedNATWithoutCTLB: Enabled
    bpfLogLevel: ""
    floatingIPs: Disabled
    healthPort: 9099
    logSeverityScreen: Info
    reportingInterval: 0s
    vxlanVNI: 4096
kind: List
metadata:
  resourceVersion: ""
