apiVersion: v1
items:
- apiVersion: operator.tigera.io/v1
  kind: Goldmane
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.tigera.io/v1","kind":"Goldmane","metadata":{"annotations":{},"name":"default"}}
    creationTimestamp: "2025-08-27T01:42:29Z"
    generation: 1
    name: default
    resourceVersion: "877181"
    uid: 6d657107-94ee-4c2e-a139-a6f20e5849cc
kind: List
metadata:
  resourceVersion: ""
