apiVersion: v1
items:
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      meta.helm.sh/release-name: nfs-provisioner
      meta.helm.sh/release-namespace: nfs-provisioner
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2025-08-28T05:33:12Z"
    labels:
      app: nfs-subdir-external-provisioner
      app.kubernetes.io/managed-by: Helm
      chart: nfs-subdir-external-provisioner-4.0.18
      heritage: Helm
      release: nfs-provisioner
    name: nfs-client
    resourceVersion: "71321"
    uid: 4b19de93-54c2-40f0-89e4-38ca17cba826
  parameters:
    archiveOnDelete: "true"
  provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
