apiVersion: v1
items:
- apiVersion: operator.tigera.io/v1
  kind: Whisker
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.tigera.io/v1","kind":"Whisker","metadata":{"annotations":{},"name":"default"}}
    creationTimestamp: "2025-08-27T01:42:29Z"
    generation: 2
    name: default
    resourceVersion: "877182"
    uid: 77e363cc-dc5f-4d04-aa25-66621666306a
  spec:
    notifications: Enabled
kind: List
metadata:
  resourceVersion: ""
