apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-frontend
  namespace: data
spec:
  replicas: 3   # 여러 노드에 분산 배치
  selector:
    matchLabels:
      app: carbon-frontend
  template:
    metadata:
      labels:
        app: carbon-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/kimkyunghyun2756/carbon_neutrality/carbon-frontend:main
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: carbon-frontend-config
          - secretRef:
              name: appdb-credentials
        ports:
          - containerPort: 8501
            protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
