apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-frontend
  namespace: data
spec:
  replicas: 1   # 보통 hostNetwork는 1개만 쓰는 게 안전 (포트 충돌 위험)
  selector:
    matchLabels:
      app: carbon-frontend
  template:
    metadata:
      labels:
        app: carbon-frontend
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: frontend
        image: ghcr.io/kimkyunghyun2756/carbon_neutrality/carbon-frontend:main
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: carbon-frontend-config
          - secretRef:
              name: appdb-credentials
        ports:
          - containerPort: 8501
            protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
