apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"k8s-app":"tigera-operator"},"name":"tigera-operator-secrets","namespace":"tigera-operator"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"tigera-operator-secrets"},"subjects":[{"kind":"ServiceAccount","name":"tigera-operator","namespace":"tigera-operator"}]}
    creationTimestamp: "2025-08-27T01:42:18Z"
    labels:
      k8s-app: tigera-operator
    name: tigera-operator-secrets
    namespace: tigera-operator
    resourceVersion: "876652"
    uid: ce450c75-fe46-49a7-a350-042705d4b688
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: tigera-operator-secrets
  subjects:
  - kind: ServiceAccount
    name: tigera-operator
    namespace: tigera-operator
kind: List
metadata:
  resourceVersion: ""
