apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:59Z"
    name: default
    namespace: kube-public
    resourceVersion: "374"
    uid: 46575a1c-9653-42a8-be08-3af1b53315fe
kind: List
metadata:
  resourceVersion: ""
