apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: default
    namespace: default
    resourceVersion: "372"
    uid: 345727fb-d2b3-4e06-bf47-a3ff3b7a6059
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","automountServiceAccountToken":false,"kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"prometheus-operator","app.kubernetes.io/version":"0.85.0"},"name":"prometheus-operator","namespace":"default"}}
    creationTimestamp: "2025-08-28T05:41:52Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/version: 0.85.0
    name: prometheus-operator
    namespace: default
    resourceVersion: "72626"
    uid: 25cce3f4-17cd-4e2d-b807-d631c456ecd4
kind: List
metadata:
  resourceVersion: ""
