apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: nfs-provisioner
      meta.helm.sh/release-namespace: nfs-provisioner
    creationTimestamp: "2025-08-28T05:33:12Z"
    labels:
      app: nfs-subdir-external-provisioner
      app.kubernetes.io/managed-by: Helm
      chart: nfs-subdir-external-provisioner-4.0.18
      heritage: Helm
      release: nfs-provisioner
    name: leader-locking-nfs-provisioner-nfs-subdir-external-provisioner
    namespace: nfs-provisioner
    resourceVersion: "71325"
    uid: 0432e6d0-d07e-459a-8aea-f2e552b67d97
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: leader-locking-nfs-provisioner-nfs-subdir-external-provisioner
  subjects:
  - kind: ServiceAccount
    name: nfs-provisioner-nfs-subdir-external-provisioner
    namespace: nfs-provisioner
kind: List
metadata:
  resourceVersion: ""
