apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      meta.helm.sh/release-name: nfs-provisioner
      meta.helm.sh/release-namespace: nfs-provisioner
    creationTimestamp: "2025-08-28T05:33:12Z"
    labels:
      app: nfs-subdir-external-provisioner
      app.kubernetes.io/managed-by: Helm
      chart: nfs-subdir-external-provisioner-4.0.18
      heritage: Helm
      release: nfs-provisioner
    name: leader-locking-nfs-provisioner-nfs-subdir-external-provisioner
    namespace: nfs-provisioner
    resourceVersion: "71324"
    uid: be2bc8c8-83c6-41b2-ac42-d717fe42f32f
  rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
kind: List
metadata:
  resourceVersion: ""
