apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-28T05:32:55Z"
    name: default
    namespace: nfs-provisioner
    resourceVersion: "71283"
    uid: 18e37dfc-c7ac-4f38-89cc-0069ac977e56
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: nfs-provisioner
      meta.helm.sh/release-namespace: nfs-provisioner
    creationTimestamp: "2025-08-28T05:33:12Z"
    labels:
      app: nfs-subdir-external-provisioner
      app.kubernetes.io/managed-by: Helm
      chart: nfs-subdir-external-provisioner-4.0.18
      heritage: Helm
      release: nfs-provisioner
    name: nfs-provisioner-nfs-subdir-external-provisioner
    namespace: nfs-provisioner
    resourceVersion: "71320"
    uid: 8b78205f-be40-4097-bea6-83caf71e75d3
kind: List
metadata:
  resourceVersion: ""
