apiVersion: v1
items:
- apiVersion: events.k8s.io/v1
  deprecatedCount: 85
  deprecatedFirstTimestamp: "2025-09-15T01:03:18Z"
  deprecatedLastTimestamp: "2025-09-16T02:40:26Z"
  deprecatedSource:
    component: kubelet
    host: k8s-master-cp
  eventTime: null
  kind: Event
  metadata:
    creationTimestamp: "2025-09-16T02:40:26Z"
    name: calico-kube-controllers-855d76474d-qvdh7.18654f191d2c1a86
    namespace: calico-system
    resourceVersion: "907252"
    uid: c972b797-f603-4420-bc47-b72ca7f6a60b
  note: Container image "docker.io/calico/kube-controllers:v3.30.2" already present
    on machine
  reason: Pulled
  regarding:
    apiVersion: v1
    fieldPath: spec.containers{calico-kube-controllers}
    kind: Pod
    name: calico-kube-controllers-855d76474d-qvdh7
    namespace: calico-system
    resourceVersion: "465672"
    uid: 1aa3c18a-f6a6-489e-be0e-d17a9f91dd10
  reportingController: kubelet
  reportingInstance: k8s-master-cp
  type: Normal
- apiVersion: events.k8s.io/v1
  deprecatedCount: 1432
  deprecatedFirstTimestamp: "2025-09-15T01:04:21Z"
  deprecatedLastTimestamp: "2025-09-16T02:50:24Z"
  deprecatedSource:
    component: kubelet
    host: k8s-master-cp
  eventTime: null
  kind: Event
  metadata:
    creationTimestamp: "2025-09-16T00:10:21Z"
    name: calico-kube-controllers-855d76474d-qvdh7.18654f27c7a480c1
    namespace: calico-system
    resourceVersion: "908042"
    uid: 669f5045-2635-4ab1-acc3-fb89e5f19964
  note: Back-off restarting failed container calico-kube-controllers in pod calico-kube-controllers-855d76474d-qvdh7_calico-system(1aa3c18a-f6a6-489e-be0e-d17a9f91dd10)
  reason: BackOff
  regarding:
    apiVersion: v1
    fieldPath: spec.containers{calico-kube-controllers}
    kind: Pod
    name: calico-kube-controllers-855d76474d-qvdh7
    namespace: calico-system
    resourceVersion: "465672"
    uid: 1aa3c18a-f6a6-489e-be0e-d17a9f91dd10
  reportingController: kubelet
  reportingInstance: k8s-master-cp
  type: Warning
- apiVersion: events.k8s.io/v1
  deprecatedCount: 75
  deprecatedFirstTimestamp: "2025-09-15T01:05:23Z"
  deprecatedLastTimestamp: "2025-09-16T02:10:23Z"
  deprecatedSource:
    component: kubelet
    host: k8s-master-cp
  eventTime: null
  kind: Event
  metadata:
    creationTimestamp: "2025-09-16T00:01:23Z"
    name: calico-kube-controllers-855d76474d-qvdh7.18654f3616f16647
    namespace: calico-system
    resourceVersion: "904865"
    uid: 18c24afa-5b15-4723-b04f-0d9b1ca2b263
  note: |
    Liveness probe failed: Error initializing datastore: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:calico-system:calico-kube-controllers" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope
  reason: Unhealthy
  regarding:
    apiVersion: v1
    fieldPath: spec.containers{calico-kube-controllers}
    kind: Pod
    name: calico-kube-controllers-855d76474d-qvdh7
    namespace: calico-system
    resourceVersion: "465672"
    uid: 1aa3c18a-f6a6-489e-be0e-d17a9f91dd10
  reportingController: kubelet
  reportingInstance: k8s-master-cp
  type: Warning
- apiVersion: events.k8s.io/v1
  deprecatedCount: 5
  deprecatedFirstTimestamp: "2025-09-16T01:33:24Z"
  deprecatedLastTimestamp: "2025-09-16T02:35:23Z"
  deprecatedSource:
    component: kubelet
    host: k8s-master-cp
  eventTime: null
  kind: Event
  metadata:
    creationTimestamp: "2025-09-16T02:35:23Z"
    name: calico-kube-controllers-855d76474d-qvdh7.18659f52307f533d
    namespace: calico-system
    resourceVersion: "906852"
    uid: 1085569b-ff56-4bd9-9cbf-b9ecd45969ab
  note: |
    (combined from similar events): Liveness probe failed: Error initializing datastore: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:calico-system:calico-kube-controllers" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope
  reason: Unhealthy
  regarding:
    apiVersion: v1
    fieldPath: spec.containers{calico-kube-controllers}
    kind: Pod
    name: calico-kube-controllers-855d76474d-qvdh7
    namespace: calico-system
    resourceVersion: "465672"
    uid: 1aa3c18a-f6a6-489e-be0e-d17a9f91dd10
  type: Warning
- apiVersion: events.k8s.io/v1
  deprecatedCount: 1766
  deprecatedFirstTimestamp: "2025-09-15T01:02:55Z"
  deprecatedLastTimestamp: "2025-09-16T02:50:26Z"
  deprecatedSource:
    component: kubelet
    host: k8s-master-cp
  eventTime: null
  kind: Event
  metadata:
    creationTimestamp: "2025-09-16T00:00:26Z"
    name: calico-node-mpnn9.18654f13915ffe84
    namespace: calico-system
    resourceVersion: "908046"
    uid: 0d46c387-7e02-4e98-9118-a4a76d4f1397
  note: Back-off restarting failed container install-cni in pod calico-node-mpnn9_calico-system(7bd8a3f4-9b6d-4a1b-ab60-548159e68a1c)
  reason: BackOff
  regarding:
    apiVersion: v1
    fieldPath: spec.initContainers{install-cni}
    kind: Pod
    name: calico-node-mpnn9
    namespace: calico-system
    resourceVersion: "876036"
    uid: 7bd8a3f4-9b6d-4a1b-ab60-548159e68a1c
  reportingController: kubelet
  reportingInstance: k8s-master-cp
  type: Warning
kind: List
metadata:
  resourceVersion: ""
