apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T01:42:39Z"
    finalizers:
    - tigera.io/cni-protector
    name: calico-cni-plugin
    namespace: calico-system
    ownerReferences:
    - apiVersion: operator.tigera.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Installation
      name: default
      uid: 55efc27a-ab47-47c5-80f3-3c474ac3753a
    resourceVersion: "1212"
    uid: ec14b275-3c9d-41a5-af02-088cc05fdc70
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T01:42:39Z"
    name: calico-kube-controllers
    namespace: calico-system
    ownerReferences:
    - apiVersion: operator.tigera.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Installation
      name: default
      uid: 55efc27a-ab47-47c5-80f3-3c474ac3753a
    resourceVersion: "1242"
    uid: e74f8ae7-a24a-4ac9-a79f-709c04190a9a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T01:42:38Z"
    finalizers:
    - tigera.io/cni-protector
    name: calico-node
    namespace: calico-system
    ownerReferences:
    - apiVersion: operator.tigera.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Installation
      name: default
      uid: 55efc27a-ab47-47c5-80f3-3c474ac3753a
    resourceVersion: "1200"
    uid: e74755f2-c172-44b7-9451-98102b1fd64a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T01:42:38Z"
    name: calico-typha
    namespace: calico-system
    ownerReferences:
    - apiVersion: operator.tigera.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Installation
      name: default
      uid: 55efc27a-ab47-47c5-80f3-3c474ac3753a
    resourceVersion: "1170"
    uid: e9c71d83-34d0-4a7d-8a5d-7693e14db147
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T01:42:39Z"
    name: csi-node-driver
    namespace: calico-system
    ownerReferences:
    - apiVersion: operator.tigera.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Installation
      name: default
      uid: 55efc27a-ab47-47c5-80f3-3c474ac3753a
    resourceVersion: "1240"
    uid: 54e60b4a-b426-4f87-8f87-ddd10af6ea00
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T01:42:38Z"
    name: default
    namespace: calico-system
    resourceVersion: "1131"
    uid: aff9791c-86ce-4e74-9009-b27e0f59dc71
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T01:42:38Z"
    name: goldmane
    namespace: calico-system
    ownerReferences:
    - apiVersion: operator.tigera.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Goldmane
      name: default
      uid: 6d657107-94ee-4c2e-a139-a6f20e5849cc
    resourceVersion: "1156"
    uid: 923221a6-889e-4847-a3fd-ca3b7b8764ea
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T01:42:38Z"
    name: whisker
    namespace: calico-system
    ownerReferences:
    - apiVersion: operator.tigera.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Whisker
      name: default
      uid: 77e363cc-dc5f-4d04-aa25-66621666306a
    resourceVersion: "1140"
    uid: fb1131b2-87cb-4a71-81fe-f2d7e835ce46
kind: List
metadata:
  resourceVersion: ""
