apiVersion: v1
kind: PersistentVolume
metadata:
  name: carbon-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["k8s-backend"]   # ← 실제 노드 이름으로! (kubectl get nodes 로 확인)
  hostPath:
    path: /srv/carbon-data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carbon-data-pvc
  namespace: data
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: carbon-data-pv
