apiVersion: v1
items:
- apiVersion: v1
  data:
    auth-extra-groups: c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=
    token-id: YXpzYjhn
    token-secret: bjN4OTN0bWxvZjRtZjg0Mg==
    usage-bootstrap-authentication: dHJ1ZQ==
    usage-bootstrap-signing: dHJ1ZQ==
  kind: Secret
  metadata:
    creationTimestamp: "2025-08-27T00:28:46Z"
    name: bootstrap-token-azsb8g
    namespace: kube-system
    resourceVersion: "296"
    uid: b5495702-4b2b-446c-8f0c-9adaf52040c3
  type: bootstrap.kubernetes.io/token
kind: List
metadata:
  resourceVersion: ""
