apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: attachdetach-controller
    namespace: kube-system
    resourceVersion: "260"
    uid: b0b205aa-7462-401e-8af8-b0a0006cb5fa
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: bootstrap-signer
    namespace: kube-system
    resourceVersion: "284"
    uid: f2d3bca1-80f4-4764-811c-8a53b03a9e4d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"calico-cni-plugin","namespace":"kube-system"}}
    creationTimestamp: "2025-08-28T06:52:13Z"
    name: calico-cni-plugin
    namespace: kube-system
    resourceVersion: "83360"
    uid: ddc03fa2-1344-4498-88c5-85b47e8a4153
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"calico-kube-controllers","namespace":"kube-system"}}
    creationTimestamp: "2025-08-28T06:52:13Z"
    name: calico-kube-controllers
    namespace: kube-system
    resourceVersion: "83355"
    uid: 31c0e1fc-66b7-437f-88f8-c6c79d4a381f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"calico-node","namespace":"kube-system"}}
    creationTimestamp: "2025-08-28T06:52:13Z"
    name: calico-node
    namespace: kube-system
    resourceVersion: "83359"
    uid: 91ff5881-a3cf-4886-8296-1ed572312c2b
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: certificate-controller
    namespace: kube-system
    resourceVersion: "259"
    uid: 50fa874d-12c3-4a76-bf4a-f29cb8c58c80
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: clusterrole-aggregation-controller
    namespace: kube-system
    resourceVersion: "266"
    uid: 6a8e4899-d1f9-4014-9955-1ce970330271
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: coredns
    namespace: kube-system
    resourceVersion: "270"
    uid: ea68d320-1b29-4a32-8fba-8239abea7eb3
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: cronjob-controller
    namespace: kube-system
    resourceVersion: "279"
    uid: f805416e-f140-4cca-be8a-9d226e7692ad
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: daemon-set-controller
    namespace: kube-system
    resourceVersion: "345"
    uid: 9a47e802-9644-4da8-b57f-ec3bbba99e4a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:59Z"
    name: default
    namespace: kube-system
    resourceVersion: "375"
    uid: 54b858f0-0208-4ffa-bf7a-c94c07ed2026
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:46Z"
    name: deployment-controller
    namespace: kube-system
    resourceVersion: "300"
    uid: 4400d56b-ff66-4866-b7be-3c6cc155a876
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:46Z"
    name: disruption-controller
    namespace: kube-system
    resourceVersion: "301"
    uid: 87cd8641-c543-431c-bd51-dbf6247d7a91
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: endpoint-controller
    namespace: kube-system
    resourceVersion: "258"
    uid: 330f7c1f-16a6-4b1e-a3e4-12c9c001d228
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: endpointslice-controller
    namespace: kube-system
    resourceVersion: "347"
    uid: 2dfceb1b-35f5-466c-9d98-ce78e81222dc
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:46Z"
    name: endpointslicemirroring-controller
    namespace: kube-system
    resourceVersion: "290"
    uid: 560b268c-046d-4c2d-b6d7-771a0b2ead13
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:47Z"
    name: ephemeral-volume-controller
    namespace: kube-system
    resourceVersion: "310"
    uid: 79afa7f3-4caf-43bb-8002-e8b7b47a6e0d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:47Z"
    name: expand-controller
    namespace: kube-system
    resourceVersion: "306"
    uid: 09dd0bfc-9aa5-4c4c-8e80-265aaab2d7a5
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:46Z"
    name: generic-garbage-collector
    namespace: kube-system
    resourceVersion: "295"
    uid: 8b5c7a11-8bf4-49f8-a442-3960fffe9faa
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: horizontal-pod-autoscaler
    namespace: kube-system
    resourceVersion: "265"
    uid: bb799286-1b58-4c4e-b4c4-25b3a0b658f8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:48Z"
    name: job-controller
    namespace: kube-system
    resourceVersion: "318"
    uid: 0a32ba0b-ba7c-4a6d-a20c-1e800fb2b6f8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: kube-proxy
    namespace: kube-system
    resourceVersion: "277"
    uid: 3271d3be-5cdc-4f53-94e9-51e456382ee3
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:47Z"
    name: legacy-service-account-token-cleaner
    namespace: kube-system
    resourceVersion: "316"
    uid: 4b09aaf6-e3f6-4de3-bf9c-03731874d185
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: namespace-controller
    namespace: kube-system
    resourceVersion: "349"
    uid: 5e5d0741-e148-4f8d-9095-65d0a4e81b27
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:46Z"
    name: node-controller
    namespace: kube-system
    resourceVersion: "302"
    uid: 591bae62-7225-4217-9e21-f71e64c5a7a1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: persistent-volume-binder
    namespace: kube-system
    resourceVersion: "350"
    uid: 2c68edc5-d033-471d-8b7f-00c168428d9f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: pod-garbage-collector
    namespace: kube-system
    resourceVersion: "342"
    uid: 8123fef8-5779-4eed-bb9b-4056a13eab7d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: pv-protection-controller
    namespace: kube-system
    resourceVersion: "262"
    uid: 7a482315-5420-4abc-88a1-43c24aa2ba8b
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:47Z"
    name: pvc-protection-controller
    namespace: kube-system
    resourceVersion: "314"
    uid: a409b234-08e5-4e70-8b66-77029e4c898a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: replicaset-controller
    namespace: kube-system
    resourceVersion: "346"
    uid: 79c0697b-880c-479b-bc7b-73589597ca70
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: replication-controller
    namespace: kube-system
    resourceVersion: "348"
    uid: 5f7fc3de-a178-470a-8105-b645ced49bf0
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: resourcequota-controller
    namespace: kube-system
    resourceVersion: "264"
    uid: f6df1e6c-4dac-42b4-8ece-1fc9225f6b9a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: root-ca-cert-publisher
    namespace: kube-system
    resourceVersion: "263"
    uid: be902d76-952c-47e1-8173-954927915fc2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:47Z"
    name: service-account-controller
    namespace: kube-system
    resourceVersion: "317"
    uid: fdcb345d-af79-4c9e-98c4-6b8a897024c4
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: service-controller
    namespace: kube-system
    resourceVersion: "343"
    uid: f52e07c4-a090-4598-891c-9498a4e33ad1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: statefulset-controller
    namespace: kube-system
    resourceVersion: "271"
    uid: ccc9cc1f-b02e-4c97-ace0-c9138ad6799b
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:48Z"
    name: token-cleaner
    namespace: kube-system
    resourceVersion: "319"
    uid: b0ea9468-f693-4601-aae5-c0cd93d0463c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:47Z"
    name: ttl-after-finished-controller
    namespace: kube-system
    resourceVersion: "315"
    uid: 0bbe4be6-8d9d-45a4-ad28-3ad467b24298
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:45Z"
    name: ttl-controller
    namespace: kube-system
    resourceVersion: "261"
    uid: a9bab13a-1e40-4a91-8092-3c28f4403ad7
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:58Z"
    name: validatingadmissionpolicy-status-controller
    namespace: kube-system
    resourceVersion: "344"
    uid: 1d69278a-170b-4df2-beae-e7104113caf2
kind: List
metadata:
  resourceVersion: ""
