apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-08-27T00:28:59Z"
    name: default
    namespace: kube-node-lease
    resourceVersion: "373"
    uid: 5f236860-3764-4631-b074-753fafa8f5a8
kind: List
metadata:
  resourceVersion: ""
