name: Build & Push & Deploy Frontend

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      fe: ${{ steps.filter.outputs.fe }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            fe:
              - 'apps/frontend/**'
              - '.github/workflows/frontend-image.yml'

  build:
    needs: changes
    if: needs.changes.outputs.fe == 'true' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/carbon-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=long

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      KUBECONFIG: /home/vagrant/.kube/config   # 러너 계정 kubeconfig 경로
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl get nodes
          kubectl set image deployment/carbon-frontend \
            frontend=ghcr.io/${{ github.repository }}/carbon-frontend:main \
            -n data
          kubectl rollout status deployment/carbon-frontend -n data

